sudo: false
language: android

jdk:
    - oraclejdk8

android:
  components:
    - build-tools-24.0.2
    - android-16
    - android-19
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-google-google_play_services

script:
    - TERM=dumb ./gradlew -i test check coveralls